services:
  mysql:
    ports:
      - "3306:3306"
    container_name: mysql-local
    volumes:
      - ./services/database/mysql/local/db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "mysql-local",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 20s
      timeout: 10s
      retries: 3

  backend:
    ports:
      - 5000:5000
    container_name: backend-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-local:5000/test"]
      interval: 20s
      timeout: 10s
      retries: 5

  frontend:
    ports:
      - 3000:3000
    container_name: frontend-local

  nginx:
    container_name: nginx-local
