services:
  mysql:
    image: mysql:8.1
    build:
      context: .
      dockerfile: ./services/database/mysql/Dockerfile-${ENV}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./services/database/mysql/seed:/docker-entrypoint-initdb.d
    user: 999:999
    networks:
      - app-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: mysql
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile-${ENV}
    container_name: backend
    volumes:
      - ./services/backend/lipAdviser:/app
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile-${ENV}
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: frontend
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    networks:
      - app-network
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      backend:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
    container_name: nginx
    environment:
      NGINX_CONF: nginx.${ENV}.conf
    networks:
      - app-network
    restart: always
    volumes:
      # Nginx設定を環境ごとに切り替え
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/nginx.${ENV}.conf:/etc/nginx/conf.d/nginx.conf

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
