services:
  mysql:
    ports:
      - "3307:3306"
    container_name: mysql-dev
    volumes:
      - ./services/database/mysql/dev/db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "mysql-dev",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 20s
      timeout: 10s
      retries: 3

  phpmyadmin:
    ports:
      - 8081:8081
    container_name: phpmyadmin-dev
    environment:
      - PMA_HOST=mysql-dev:3307

  backend:
    ports:
      - 5001:5001
    container_name: backend-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-dev:5001/test"]
      interval: 20s
      timeout: 10s
      retries: 5

  frontend:
    ports:
      - 3001:3001
    container_name: frontend-dev

  nginx:
    container_name: nginx-dev
