services:
  mysql:
    ports:
      - "3306:3306"
    container_name: mysql-prod
    volumes:
      - ./services/database/mysql/prod/db:/var/lib/mysql
      - ./services/database/mysql/prod/config/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "mysql-prod",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 20s
      timeout: 10s
      retries: 3

  phpmyadmin:
    ports:
      - 8080:8080
    container_name: phpmyadmin-prod
    environment:
      - PMA_HOST=mysql-prod:3306

  backend:
    ports:
      - 5000:5000
    container_name: backend-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-prod:5000/test"]
      interval: 20s
      timeout: 10s
      retries: 5

  frontend:
    ports:
      - 3000:3000
    container_name: frontend-prod

  nginx:
    container_name: nginx-prod
