# Pythonベースのイメージを使用
FROM python:3.12-slim

# 作業ディレクトリを設定
WORKDIR /app

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gcc \
    g++ \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libtiff-dev \
    libgl1-mesa-glx \
    libopencv-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# 必要なパッケージをインストール
COPY ./services/backend/lipAdviser/requirements.txt /app/
RUN python3 -m pip install gunicorn
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# ソースコードをコピー
COPY ./services/backend/lipAdviser/ .

# gunicornでアプリケーションを起動
CMD ["gunicorn", "API.mainApp:app", "--workers=4", "-b", "0.0.0.0:5000"]

# ポートの開放
EXPOSE 5000
