# バックエンド用Dockerfile

# Python の公式イメージをベースに使用
FROM python:3.12-alpine

# curlをインストール
RUN apk add --no-cache curl

# 作業ディレクトリを設定
WORKDIR /app

# 必要なパッケージをインストール
COPY ./services/backend/lipAdviser/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# ソースコードをコピー
COPY ./services/backend/lipAdviser/ .

# 環境変数でポートを指定する
ENV FLASK_APP=API.mainApp
ENV FLASK_RUN_PORT=5000

# Flaskアプリケーションを実行
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]

# ポートの開放
EXPOSE 5000
