FROM node:20-alpine

# 作業ディレクトリを設定
WORKDIR /app

# 必要なパッケージの依存関係をインストール
# GitHubの認証トークンを使って、npmパッケージをインストールできるように設定
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=${GITHUB_TOKEN}
ENV PORT=3000

COPY ./services/frontend/.npmrc .npmrc

# パッケージの依存関係をインストール
COPY ./services/frontend/ffoffa/package.json ./
RUN npm install --frozen-lockfile

# ソースコードをコピー
COPY ./services/frontend/ffoffa/ .

# Next.js アプリケーションをビルド
RUN  npm run build

# 環境変数を設定
ENV NODE_ENV=production

# .env ファイルは不要なので削除
RUN rm -f .npmrc

# Next.js アプリケーションを起動
CMD ["npm", "run", "start"]
